apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-metrics-yaml
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    ---
    set_timestamp: false
    metrics:

    #### ELB
    - aws_namespace: AWS/ELB
      aws_metric_name: UnHealthyHostCount
      aws_dimensions: [AvailabilityZone, LoadBalancerName]
      aws_statistics: [Average]

    - aws_namespace: AWS/ELB
      aws_metric_name: RequestCount
      aws_dimensions: [AvailabilityZone, LoadBalancerName]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ELB
      aws_metric_name: Latency
      aws_dimensions: [AvailabilityZone, LoadBalancerName]
      aws_statistics: [Average]

    - aws_namespace: AWS/ELB
      aws_metric_name: SurgeQueueLength
      aws_dimensions: [AvailabilityZone, LoadBalancerName]
      aws_statistics: [Maximum, Sum]

    #### RDS
    - aws_namespace: AWS/RDS
      aws_metric_name: CPUUtilization
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: WriteIOPS
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: ReadIOPS
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: ReadLatency
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: WriteLatency
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: FreeableMemory
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: FreeStorageSpace
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: NetworkReceiveThroughtpu
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    - aws_namespace: AWS/RDS
      aws_metric_name: NetworkTransmitThroughtpu
      aws_dimensions: [DBInstanceIdentifier]
      aws_statistics: [Average]

    #### Api GW
    - aws_namespace: AWS/ApiGateway
      aws_metric_name: 4XXError
      aws_dimensions: [ApiName, Stage]
      aws_statistics: [Sum]

    - aws_namespace: AWS/ApiGateway
      aws_metric_name: 5XXError
      aws_dimensions: [ApiName, Stage]
      aws_statistics: [Sum]

    #### Lambda

    - aws_namespace: AWS/Lambda
      aws_metric_name: Errors
      aws_dimensions: [FunctionName]
      aws_statistics: [Sum]