{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudwatch-exporter.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "cloudwatch-exporter.labels" . | nindent 4 }}
  annotations:
      # Substitute your account ID and IAM service role name below.
      eks.amazonaws.com/role-arn: "{{ .Values.roleArn }}"
{{- end -}}