apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudwatch-exporter.fullname" . }}
  labels:
    {{- include "cloudwatch-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudwatch-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "9106"
          prometheus.io/scrape-slow: "true"
          iam.amazonaws.com/role: "{{ .Values.roleArn }}"
      labels:
        {{- include "cloudwatch-exporter.selectorLabels" . | nindent 8 }}
        entorno: {{ .Values.entorno }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cloudwatch-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /config/config.yml
            name: cloudwatch-metrics-volume
            subPath: config.yaml
          env:
          - name: AWS_DEFAULT_REGION
            value: "{{ .Values.awsRegion }}"   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - configMap:
          defaultMode: 420
          name: cloudwatch-metrics-yaml
        name: cloudwatch-metrics-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
