{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "cloudwatch-exporter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cloudwatch-exporter.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudwatch-exporter.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end -}}
